config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
get 'estimate_entries', :to => 'estimates#index'

resources :estimate_entries, :controller => 'estimates', :except => :destroy do
  collection do
    get 'report'
    get 'bulk_edit'
    post 'bulk_update'
  end
end
match '/estimate_entries/:id', :to => 'estimates#destroy', :via => :delete, :id => /\d+/
# TODO: delete /estimate_entries for bulk deletion
match '/estimate_entries/destroy', :to => 'estimates#destroy', :via => :delete

resources :issues do
  resources :estimate_entries, :controller => 'estimates' do
    collection do
      get 'report'
      post 'new'
    end

    patch :accept, on: :member
  end
end

resources :projects do
  resources :estimate_entries, :controller => 'estimates' do
    get 'report', :on => :collection
  end
end

app/views/issues/_action_menu.html.erb
<%= stylesheet_link_tag 'style', :plugin => 'redmine_estimates' %>
<div class="contextual">
<%= link_to l(:button_edit), edit_issue_path(@issue), :onclick => 'showAndScrollTo("update", "issue_notes"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit) if @issue.editable? %>
<%= link_to l(:button_log_time), new_issue_time_entry_path(@issue), :class => 'icon icon-time-add' if User.current.allowed_to?(:log_time, @project) %>
<%= link_to l(:label_add_estimate), new_issue_estimate_entry_path(@issue), :class => 'icon icon-estimate-add'  %>
<%= watcher_link(@issue, User.current) %>
<%= link_to l(:button_copy), project_copy_issue_path(@project, @issue), :class => 'icon icon-copy' if User.current.allowed_to?(:add_issues, @project) %>
<%= link_to l(:button_delete), issue_path(@issue), :data => {:confirm => issues_destroy_confirmation_message(@issue)}, :method => :delete, :class => 'icon icon-del' if User.current.allowed_to?(:delete_issues, @project) %>
</div>

app/views/issues/_edit.html.erb
<%= labelled_form_for @issue, :html => {:id => 'issue-form', :multipart => true} do |f| %>
    <%= error_messages_for 'issue', 'time_entry', 'estimate_entry' %>
    <%= render :partial => 'conflict' if @conflict %>
    <div class="box">
    <% if @edit_allowed || !@allowed_statuses.empty? %>
        <fieldset class="tabular"><legend><%= l(:label_change_properties) %></legend>
        <div id="all_attributes">
        <%= render :partial => 'form', :locals => {:f => f} %>
        </div>
        </fieldset>
    <% end %>
    <%= labelled_fields_for :estimate_entry, @estimate_entry do |estimates_entry| %>
        <fieldset class="tabular"><legend><%= l(:label_estimated_time) %></legend>

            <div class="splitcontentleft">
                <p><%= estimates_entry.text_field :hours, :size => 6, :label => :label_estimate %> <%= l(:field_hours) %></p>
            </div>
            <div class="splitcontentleft">
                <p><%= estimates_entry.select :activity_id, activity_collection_for_select_options %></p>
            </div>

            <p><%= estimates_entry.text_field :comments, :size => 60, :style => 'width: 90%' %></p>

        </fieldset>

    <% end %>
    <% if User.current.allowed_to?(:log_time, @project) %>
        <fieldset class="tabular"><legend><%= l(:button_log_time) %></legend>
        <%= labelled_fields_for :time_entry, @time_entry do |time_entry| %>
        <div class="splitcontentleft">
        <p><%= time_entry.text_field :hours, :size => 6, :label => :label_spent_time %> <%= l(:field_hours) %></p>
        </div>
        <div class="splitcontentright">
        <p><%= time_entry.select :activity_id, activity_collection_for_select_options %></p>
        </div>
        <p><%= time_entry.text_field :comments, :size => 60 %></p>
        <% @time_entry.custom_field_values.each do |value| %>
          <p><%= custom_field_tag_with_label :time_entry, value %></p>
        <% end %>
        <% end %>
    </fieldset>
    <% end %>

    <fieldset><legend><%= l(:field_notes) %></legend>
    <%= f.text_area :notes, :cols => 60, :rows => 10, :class => 'wiki-edit', :no_label => true %>
    <%= wikitoolbar_for 'issue_notes' %>

    <% if @issue.safe_attribute? 'private_notes' %>
    <%= f.check_box :private_notes, :no_label => true %> <label for="issue_private_notes"><%= l(:field_private_notes) %></label>
    <% end %>

    <%= call_hook(:view_issues_edit_notes_bottom, { :issue => @issue, :notes => @notes, :form => f }) %>
    </fieldset>

    <fieldset><legend><%= l(:label_attachment_plural) %></legend>
    <p><%= render :partial => 'attachments/form', :locals => {:container => @issue} %></p>
    </fieldset>
    </div>

    <%= f.hidden_field :lock_version %>
    <%= hidden_field_tag 'last_journal_id', params[:last_journal_id] || @issue.last_journal_id %>
    <%= submit_tag l(:button_submit) %>
    <%= preview_link preview_edit_issue_path(:project_id => @project, :id => @issue), 'issue-form' %>
    | <%= link_to l(:button_cancel), {}, :onclick => "$('#update').hide(); return false;" %>
<% end %>
<div id="preview" class="wiki"></div>

app/views/issues/_estimates.html.erb
<% content_for :header_tags do %>
		<%= javascript_include_tag "plugin.js", :plugin => 'redmine_estimates' %>
<% end %>



<p><strong><%= l(:label_issue_estimates) %></strong></p>
<div class="autoscroll">
	<table id="estimate-entries" class="list time-entries">
		
		<thead>
			<tr>
				<th><a href= <%= issue_estimate_entries_path(@issue.id) + "?sort=spent_on" %> class="sort desc"><%= l(:label_date) %></a></th>
				<th><a href= <%= issue_estimate_entries_path(@issue.id) + "?sort=user%2Cspent_on%3Adesc" %> ><%= l(:field_user) %></a></th> 
				<th><a href= <%= issue_estimate_entries_path(@issue.id) + "?sort=activity,spent_on:desc" %> ><%= l(:field_activity) %></a></th>
				<th><a href= <%= issue_estimate_entries_path(@issue.id) + "?sort=hours%2Cspent_on"%> ><%= l(:label_estimate) %></a></th>
				<th><%= l(:field_comments) %></th>
				<th><%= l(:label_estimates_actions) %></th>
				<th></th>

			</tr>
		</thead>
		<tbody>
			<style type="text/css">
				.hidden{
					display: none;
				}
			</style>
			<script type="text/javascript">
			
			</script>
			<% @estimates.each do |entry| -%>
			
			<tr class="time-entry " 
				data-is-accepted="<%= entry.is_accepted %>" >

			<%= labelled_form_for entry,  :url => accept_issue_estimate_entry_path(entry.issue_id, entry.id) do -%>

			<%= hidden_field_tag 'back_url', url_for(params) %>

				<td>
					<%= entry.spent_on %>
				</td>
				<td>
					<%= User.find(entry.user_id ).name %>
				</td>
				<td>
					<%= Enumeration.find(entry.activity_id).name %>
				</td>
				<td>
					<%= entry.hours %>
				</td>
				<td>
					<%= entry.comments %>
				</td>
				<td>
					 <% if (entry.editable_by?(User.current)) || User.current.admin?  -%>
						 <% if !entry.is_accepted  -%>
							<input id="estimate_entry_hours" type="hidden" name="estimate_entry[is_accepted]"  size="6" type="text" value=1 >
						 	<%= button_tag l(:button_accept), :style => "background-color: #57a957; border-radius: 5px; color: white" %> 
						
						<% elsif (entry.updated_on.utc  > (Time.now - 60.seconds).utc) || User.current.admin?  %>
							<input id="estimate_entry_hours" type="hidden" name="estimate_entry[is_accepted]"  size="6" type="text" value=0 >
						 	<%= button_tag l(:button_cancel_estimate), :style => "background-color: #e37d7d; border-radius: 5px; color: white" %> 

						<% else %>
						<span style="color:#808080"><%= l(:label_estimation_is_accepted) %></span>						 	
						 <% end %>

    				<% end -%>
				</td>
				<td>
					<% if (entry.created_on.utc  > (Time.now - 60.seconds).utc) || User.current.allowed_to?(:edit_estimates, @project) ||  User.current.admin? %>
				        <%= link_to image_tag('edit.png'),  edit_estimate_entry_path(entry),
				                                           :title => l(:button_edit) %>
				        <%= link_to image_tag('delete.png'), estimate_entry_path(entry),
				                                             :data => {:confirm => l(:text_are_you_sure)},
				                                             :method => :delete,
				                                             :title => l(:button_delete) %>
				      	<% end %>
				</td>
				<% end %>
			
			</tr>
			<% end -%>
		</tbody>
	</table>
	
</div>
<input type="checkbox" name="show_accepted" id="accepted_estimates">
<label for="accepted_estimates"> <span style="text-decoration: underline"><%= l(:link_show_accepted_estimates) %></span></label>

<%= link_to image_tag('estimate_clock_icon.png', :plugin => 'redmine_estimates') + l(:label_add_estimate), new_issue_estimate_entry_path(@issue) %>

app/views/issues/show.html.erb
<%= render :partial => 'action_menu' %>

<h2><%= issue_heading(@issue) %></h2>

<div class="<%= @issue.css_classes %> details">
  <% if @prev_issue_id || @next_issue_id %>
      <div class="next-prev-links contextual">
        <%= link_to_if @prev_issue_id,
                       "\xc2\xab #{l(:label_previous)}",
                       (@prev_issue_id ? issue_path(@prev_issue_id) : nil),
                       :title => "##{@prev_issue_id}",
                       :accesskey => accesskey(:previous) %> |
        <% if @issue_position && @issue_count %>
            <span class="position"><%= l(:label_item_position, :position => @issue_position, :count => @issue_count) %></span>
            |
        <% end %>
        <%= link_to_if @next_issue_id,
                       "#{l(:label_next)} \xc2\xbb",
                       (@next_issue_id ? issue_path(@next_issue_id) : nil),
                       :title => "##{@next_issue_id}",
                       :accesskey => accesskey(:next) %>
      </div>
  <% end %>

  <%= avatar(@issue.author, :size => "50") %>

  <div class="subject">
    <%= render_issue_subject_with_tree(@issue) %>
  </div>
  <p class="author">
    <%= authoring @issue.created_on, @issue.author %>.
    <% if @issue.created_on != @issue.updated_on %>
        <%= l(:label_updated_time, time_tag(@issue.updated_on)).html_safe %>.
    <% end %>
  </p>

  <div class="attributes">
    <%= issue_fields_rows do |rows|
      rows.left l(:field_status), @issue.status.name, :class => 'status'
      rows.left l(:field_priority), @issue.priority.name, :class => 'priority'

      unless @issue.disabled_core_fields.include?('assigned_to_id')
        rows.left l(:field_assigned_to), avatar(@issue.assigned_to, :size => "14").to_s.html_safe + (@issue.assigned_to ? link_to_user(@issue.assigned_to) : "-"), :class => 'assigned-to'
      end
      unless @issue.disabled_core_fields.include?('category_id') || (@issue.category.nil? && @issue.project.issue_categories.none?)
        rows.left l(:field_category), (@issue.category ? @issue.category.name : "-"), :class => 'category'
      end
      unless @issue.disabled_core_fields.include?('fixed_version_id') || (@issue.fixed_version.nil? && @issue.assignable_versions.none?)
        rows.left l(:field_fixed_version), (@issue.fixed_version ? link_to_version(@issue.fixed_version) : "-"), :class => 'fixed-version'
      end

      unless @issue.disabled_core_fields.include?('start_date')
        rows.right l(:field_start_date), format_date(@issue.start_date), :class => 'start-date'
      end
      unless @issue.disabled_core_fields.include?('due_date')
        rows.right l(:field_due_date), format_date(@issue.due_date), :class => 'due-date'
      end
      unless @issue.disabled_core_fields.include?('done_ratio')
        rows.right l(:field_done_ratio), progress_bar(@issue.done_ratio, :width => '80px', :legend => "#{@issue.done_ratio}%"), :class => 'progress'
      end
      unless @issue.disabled_core_fields.include?('estimated_hours')
        unless @issue.estimated_hours.nil?
          rows.right l(:field_estimated_hours), l_hours(@issue.estimated_hours), :class => 'estimated-hours'
        end
      end
      if User.current.allowed_to?(:view_time_entries, @project)
        rows.right l(:label_spent_time), (@issue.total_spent_hours > 0 ? link_to(l_hours(@issue.total_spent_hours), issue_time_entries_path(@issue)) : "-"), :class => 'spent-time'
      end

      if User.current.allowed_to?(:view_time_entries, @project)
        rows.right l(:label_estimate_time), (@issue.total_estimate_hours > 0 ? link_to(l_hours(@issue.total_estimate_hours), issue_estimate_entries_path(@issue)) : "-"), :class => 'spent-time'
        rows.right l(:label_estimate_accepted_time), (@issue.total_accepted_estimate_hours > 0 ? l_hours(@issue.total_accepted_estimate_hours) : "-"), :class => 'spent-time'
      end
    end %>

    <%= render_custom_fields_rows(@issue) %>
    <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
  </div>

  <% if @issue.description? || @issue.attachments.any? -%>
      <hr/>
      <% if @issue.description? %>
          <div class="description">
            <div class="contextual">
              <%= link_to l(:button_quote), quoted_issue_path(@issue), :remote => true, :method => 'post', :class => 'icon icon-comment' if @issue.notes_addable? %>
            </div>

            <p><strong><%= l(:field_description) %></strong></p>
            <div class="wiki">
              <%= textilizable @issue, :description, :attachments => @issue.attachments %>
            </div>
          </div>
      <% end %>
      <%= link_to_attachments @issue, :thumbnails => true %>
  <% end -%>

  <%= call_hook(:view_issues_show_description_bottom, :issue => @issue) %>

  <% if !@issue.leaf? || User.current.allowed_to?(:manage_subtasks, @project) %>
      <hr/>
      <div id="issue_tree">
        <div class="contextual">
          <%= link_to_new_subtask(@issue) if User.current.allowed_to?(:manage_subtasks, @project) %>
        </div>
        <p><strong><%= l(:label_subtask_plural) %></strong></p>
        <%= render_descendants_tree(@issue) unless @issue.leaf? %>
      </div>
  <% end %>

  <% if @relations.present? || User.current.allowed_to?(:manage_issue_relations, @project) %>
      <hr/>
      <div id="relations">
        <%= render :partial => 'relations' %>
      </div>
  <% end %>

  <% if @estimates.present? %>
      <div id="relations">
        <hr/>
        <%= render :partial => 'estimates' %>
      </div>
  <% end %>
</div>

<% if @changesets.present? %>
    <div id="issue-changesets">
      <h3><%= l(:label_associated_revisions) %></h3>
      <%= render :partial => 'changesets', :locals => {:changesets => @changesets} %>
    </div>
<% end %>

<% if @journals.present? %>
    <div id="history">
      <h3><%= l(:label_history) %></h3>
      <%= render :partial => 'history', :locals => {:issue => @issue, :journals => @journals} %>
    </div>
<% end %>


<div style="clear: both;"></div>
<%= render :partial => 'action_menu' %>

<div style="clear: both;"></div>
<% if @issue.editable? %>
    <div id="update" style="display:none;">
      <h3><%= l(:button_edit) %></h3>
      <%= render :partial => 'edit' %>
    </div>
<% end %>

<% other_formats_links do |f| %>
    <%= f.link_to 'Atom', :url => {:key => User.current.rss_key} %>
    <%= f.link_to 'PDF' %>
<% end %>

<% html_title "#{@issue.tracker.name} ##{@issue.id}: #{@issue.subject}" %>

<% content_for :sidebar do %>
    <%= render :partial => 'issues/sidebar' %>

    <% if User.current.allowed_to?(:add_issue_watchers, @project) ||
        (@issue.watchers.present? && User.current.allowed_to?(:view_issue_watchers, @project)) %>
        <div id="watchers">
          <%= render :partial => 'watchers/watchers', :locals => {:watched => @issue} %>
        </div>
    <% end %>
<% end %>